### ISSUE TITLE
Unable to parse permissions with empty string

### ISSUE THREAD

**Issue by dcarley** [terraform-providers/terraform-provider-rabbitmq#42]
### Terraform Version
```
$ terraform -v
Terraform v0.12.13
+ provider.rabbitmq v1.1.0
```

### Affected Resource(s)

- rabbitmq_permissions

### Terraform Configuration Files
```hcl
resource "rabbitmq_user" "readonly" {
  name     = "readonly"
  password = "readonly"
  tags     = ["management"]
}

resource "rabbitmq_permissions" "readonly" {
  user  = rabbitmq_user.readonly.name
  vhost = "/"

  permissions {
    configure = ""
    write     = ""
    read      = ""
  }
}
```

### Debug Output
N/A?

### Panic Output
N/A

### Expected Behavior
It should apply successfully and give the user "empty" permissions to the vhost.

### Actual Behavior

```
rabbitmq_user.readonly: Creating...
rabbitmq_user.readonly: Creation complete after 0s [id=readonly]
rabbitmq_permissions.readonly: Creating...

Error: Unable to parse permissions

  on main.tf line 7, in resource "rabbitmq_permissions" "readonly":
   7: resource "rabbitmq_permissions" "readonly" {
```

### Steps to Reproduce
1. Create a file with the config from above
1. `terraform apply`

### Important Factoids
Tested against RabbitMQ 3.7.21

Workaround is to specify `^$`.

### References
N/A

**Comment by aminueza** [comment]
Hi @dcarley ,

Permissions cannot be empty because [configure, write and read env are required](https://github.com/terraform-providers/terraform-provider-rabbitmq/blob/b44cf3c974613dd7dfbb066967ee886e5988acfd/rabbitmq/resource_permissions.go#L45). A way to fix: add as an optional env with a default value.

**Comment by cyrilgdn** [comment]
@dcarley @aminueza I've just create a little PR #52 to fix this. Could one of you review it ?

>  cannot be empty because configure, write and read env are required

Not really because actually, if you don't specify them (e.g. with an empty block ``permissions{}``), Terraform will complain about the missing required fields.

In this case, we specified them, but as empty string is the "null" value of the type string, Terraform seems to remove them when parsing the permissions and this ends up a nil value in the permissions list.

**Comment by aminueza** [comment]
I've reviewed and approved your PR. The changes are working with empty string now. I'm going to looking for if there are others issues regarding empty string. Thank you @cyrilgdn for the explanation.

**Comment by cyrilgdn** [comment]
I'll try to do create a new release this week. I'll let you know here when it's done.
